#ifndef EFFECTS_H
#define EFFECTS_H

#include "globals.h"

void generateLine();
void shiftUp();
void drawFrame(uint8_t pcnt, bool isColored);
uint8_t wrapX(int8_t x);
uint8_t wrapY(int8_t y);

void whiteColorStripeRoutine();
void colorRoutine();
void colorsRoutine2();
void madnessNoiseRoutine();
void cloudsNoiseRoutine();
void lavaNoiseRoutine();
void plasmaNoiseRoutine();
void rainbowNoiseRoutine();
void rainbowStripeNoiseRoutine();
void zebraNoiseRoutine();
void forestNoiseRoutine();
void oceanNoiseRoutine();
void BBallsRoutine();
void bounceRoutine();
void popcornRoutine();
void spiroRoutine();
void PrismataRoutine();
void smokeballsRoutine();
void execStringsFlame();
void Fire2021Routine();
void pacificRoutine();
void shadowsRoutine();
void DNARoutine();
void flockRoutine(bool predatorIs);
void butterflysRoutine(bool isColored);
void snakesRoutine();
void nexusRoutine();
void spheresRoutine();
void Sinusoid3Routine();
void MetaBallsRoutine();
void polarRoutine();
void spiderRoutine();
void LavaLampRoutine();
void LiquidLampRoutine(bool isColored);
void newMatrixRoutine();
void matrixRoutine();
void fire2012again();
void Fire2018_2();
void fire2020Routine2();
void fireRoutine(bool isColored);
void whirlRoutine(bool oneColor);
void magmaRoutine();
void LLandRoutine();
void fire2012WithPalette();
void fire2012WithPalette4in1();
void poolRoutine();
void pulseRoutine(uint8_t PMode);
void oscillatingRoutine();
void starfield2Routine();
void fairyRoutine();
void RainbowCometRoutine();
void ColorCometRoutine();
void MultipleStream();
void MultipleStream2();
void lumenjerRoutine();
void attractRoutine();
void MultipleStream3();
void MultipleStream5();
void MultipleStream8();
void sparklesRoutine();
void twinklesRoutine();
void MultipleStreamSmoke(bool isColored);
void picassoSelector();
void WaveRoutine();
void sandRoutine();
void ringsRoutine();
void cube2dRoutine();
void simpleRain();
void stormyRain();
void coloredRain();
void RainRoutine();
void snowRoutine();
void stormRoutine2();
void LeapersRoutine();
void lightersRoutine();
void ballsRoutine();
void lightBallsRoutine();
void rainbowRoutine();
void BotswanaRivers();
void Swirl();
void Ukraine();
void colorsWine();
void OilPaints();
void Watercolor();
void FeatherCandleRoutine();
void text_running();

#endif
